/**
 *This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
 *Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
 */

package
{
	import flash.display.Sprite;
	import somasim.math.random.TinyMTTest;
	import somasim.math.random.MersenneTwisterTest;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		private var somasim_math_random_MersenneTwisterTests_obj:somasim.math.random.MersenneTwisterTest;
		private var somasim_math_random_TinyMTTests_obj:somasim.math.random.TinyMTTest;
	}
}